# Generated by Django 5.2.7 on 2025-10-22 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=30, unique=True)),
                ("timestamp", models.DateField(default=datetime.date.today)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
