# Generated by Django 5.2.7 on 2025-10-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={"ordering": ["created"]},
        ),
    ]
