# Generated by Django 5.2.7 on 2025-10-23 08:20

import datetime

from django.db import migrations, models

import quotes.validators


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_quote_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="timestamp",
            field=models.DateField(
                default=datetime.date.today,
                validators=[quotes.validators.validate_date],
            ),
        ),
    ]
