# Generated by Django 5.2.7 on 2026-05-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_alter_quote_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={"ordering": ["-created"]},
        ),
    ]
