# Generated by Django 5.2.7 on 2026-05-30 13:32

from django.db import migrations, models


def backfill_author_lower(apps, schema_editor):
    quote_model = apps.get_model("quotes", "Quote")
    for quote in quote_model.objects.all().iterator():
        quote_model.objects.filter(pk=quote.pk).update(
            author_lower=quote.author.lower()
        )


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_alter_quote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="author_lower",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=100
            ),
        ),
        migrations.RunPython(backfill_author_lower, migrations.RunPython.noop),
    ]
